#!/bin/sh

# $Id$
#
# init script for ds-graphd
#
# chkconfig: 2345 82 28
# description: fedora-ds-graph Fedora DS log grapher.
#
# processname: ds-graphd
# pidfile: /var/run/ds-graph.pid

# fedora-ds-graph -- An rrdtool-based graphing tool for Fedora DS statistics
# copyright (c) 2006-2008 Chris St. Pierre <stpierre@nebrwesleyan.edu>
# based on mailgraph copyright (c) 2000-2005 David Schweikert <dws@ee.ethz.ch>
# released under the GNU General Public License

# Source function library.
. /etc/init.d/functions

LOCK_FILE=/var/lock/subsys/ds-graph

[ -e /etc/sysconfig/ds-graph ] && . /etc/sysconfig/ds-graph

case "$1" in
    'start')
	if [ "x${LOGFILE}" != "x" ]; then
	    ARGS="-l ${LOGFILE}"
	else
	    ARGS="-I ${INSTANCE}"
	fi

	if [ "x${PIDFILE}" != "x" ]; then
	    ARGS="${ARGS} --pidfile=${PID_FILE}"
	fi

	ARGS="${ARGS} -d --rrddir=${RRD_DIR}"

	echo -n "Starting ds-graph";
	daemon ${DS_GRAPHD} ${ARGS}
	RETVAL=$?
	echo
	[ ${RETVAL} -eq 0 ] && touch ${LOCK_FILE}
	exit ${RETVAL}
	;;

    'stop')
	echo -n "Stopping ds-graph";
	killproc ${DS_GRAPHD}
	RETVAL=$?
	echo
	[ ${RETVAL} -eq 0 ] && rm ${LOCK_FILE}
	exit ${RETVAL}
	;;

    'restart')
	$0 stop; $0 start;
	;;

    *)
	echo "Usage: $0 { start | stop | restart }"
	exit 1
	;;

esac
exit 0
