#!/bin/sh

# $Id$
#
# init script for ldapgraphd
#
# chkconfig: 2345 82 28
# description: ldapgraph LDAP log grapher.
#
# processname: ldapgraphd
# pidfile: /var/run/ldapgraph.pid

# ldapgraph -- An rrdtool-based graphing tool for LDAP server (389DS,
#              RHDS, Sun DS, OpenLDAP statistics)
# copyright (c) 2006-2011 Chris St. Pierre <chris.a.st.pierre@gmail.com>
# based on mailgraph copyright (c) 2000-2005 David Schweikert <dws@ee.ethz.ch>
# released under the GNU General Public License

# Source function library.
. /etc/init.d/functions

LOCK_FILE=/var/lock/subsys/ldapgraph

[ -e /etc/sysconfig/ldapgraph ] && . /etc/sysconfig/ldapgraph

case "$1" in
    'start')
	if [ -n ${LOGFILE} ]; then
	    ARGS="-l ${LOGFILE}"
	else
	    ARGS="-I ${INSTANCE}"
	fi

	if [ -n ${PIDFILE} ]; then
	    ARGS="${ARGS} --pidfile=${PID_FILE}"
	fi

        if [ -z $LDAPGRAPHD ]; then
            LDAPGRAPHD=ldapgraphd
        fi

	ARGS="${ARGS} -d --rrddir=${RRD_DIR}"

	echo -n "Starting ldapgraph";
	daemon ${LDAPGRAPHD} ${ARGS}
	RETVAL=$?
	echo
	[ ${RETVAL} -eq 0 ] && touch ${LOCK_FILE}
	exit ${RETVAL}
	;;

    'stop')
	echo -n "Stopping ldapgraph";
	killproc ${LDAPGRAPHD}
	RETVAL=$?
	echo
	[ ${RETVAL} -eq 0 ] && rm ${LOCK_FILE}
	exit ${RETVAL}
	;;

    'restart')
	$0 stop; $0 start;
	;;

    *)
	echo "Usage: $0 { start | stop | restart }"
	exit 1
	;;

esac
exit 0
