#!/bin/sh

# init script for fdsgraph
#
# chkconfig: 2345 82 28
# description: fdsgraph Fedora DS log grapher.
#
# processname: fdsgraph.pl
# pidfile: /var/run/fdsgraph.pid

# fdsgraph -- An rrdtool-based graphing tool for Fedora DS statistics
# copyright (c) 2006 Chris St. Pierre <stpierre@nebrwesleyan.edu>
# based on mailgraph copyright (c) 2000-2005 David Schweikert <dws@ee.ethz.ch>
# released under the GNU General Public License

PATH=/bin:/usr/bin
FDSGRAPH_PL=/usr/local/bin/fdsgraph.pl
PID_FILE=/var/run/fdsgraph.pid
RRD_DIR=/var/lib/fdsgraph

case "$1" in
'start')
	echo "Starting fdsgraph";
	if [ -e $PID_FILE ]; then
	    echo "fdsgraph already running";
	else
	    nice -19 $FDSGRAPH_PL -d --daemon-pid=$PID_FILE \
		--daemon-rrd=$RRD_DIR
	fi
	;;

'stop')
	echo "Stopping fdsgraph";
	if [ -f $PID_FILE ]; then
		kill `cat $PID_FILE`
		rm $PID_FILE
	else
		echo "fdsgraph not running";
	fi
	;;

'restart')
	$0 stop; $0 start;
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;

esac
exit 0
